import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { isCompletedMonth, selectMonthlyMemories } from "./monthly-memory.js";

assert.equal(isCompletedMonth(2026, 7, "2026-09-06"), true);
assert.equal(isCompletedMonth(2026, 8, "2026-09-06"), false);
assert.equal(isCompletedMonth(2026, 9, "2026-09-06"), false);
assert.equal(isCompletedMonth(2025, 11, "2026-01-01"), true);
const records = [4, 15, 16, 20].map(day => ({ date: `2026-09-${String(day).padStart(2, "0")}`, question: "질문", answer: "답" }));
assert.deepEqual(selectMonthlyMemories(records, 2026, 8).map(record => record.date), ["2026-09-04", "2026-09-15", "2026-09-20"]);
const app = readFileSync("app.js", "utf8");
const keepsake = app.slice(app.indexOf("function renderMonthlyKeepsake()"), app.indexOf("function renderMonthlyKeepsakeExport("));
assert.match(keepsake, /answersInViewedMonth\(\)/);
assert.match(keepsake, /selectMonthlyMemories\(records, year, month\)/);
assert.match(keepsake, /answerText\(record\)/);
assert.match(keepsake, /isCompletedMonth\(year, month, syncToday\(\)\)/);
assert.doesNotMatch(keepsake, /localStorage|roomBackend|Math\.random|fetch\(|animalName|runtimePetState/);
const monthlyMemory = app.slice(app.indexOf("function renderMonthlyMemory()"), app.indexOf("function renderMonthlyKeepsake()"));
assert.match(monthlyMemory, /keepsakeEntry\.classList\.toggle\("is-hidden", !isCompletedMonth\(year, month, syncToday\(\)\)\)/);
assert.match(app, /monthly-keepsake-back"\)\.addEventListener\("click", \(\) => showView\("monthly-memory"\)\)/);
console.log("phase 5B monthly keepsake checks passed");
